### PR TITLE
A Docker Compose setup with Hardhat

### PR DESCRIPTION
**Pull request by neysofu**
This PR introduces a Docker Compose setup which is intended to replace our current Overmind orchestration scripts.

The build file can be found at `k8s/compose/docker-compose.yml`. Several services are included:

- `graph-node`
- `block-oracle`
- `ipfs`
- `postgres`
- `hardhat`
- `contracts`
- `epoch-subgraph`

Depedendencies across these services are managed via `restart:` and `depends_on:`. Although I've been careful to only start services once all dependencies were ready, it's possible some race conditions slipped through and I would appreciate a bug report if so.

`$ cd k8s/compose && docker compose up`

### CODE REVIEW

**Comment by tilacog** [comment]
I tried running locally, but the `block-oracle` job fails due to:

```
environment variable not found for key `epoch_manager_address` 
```

We would need to provide that environment variable for the job, but the problem is that the address is only known after deployment __(which happens in the `contracts` job)__. 

We would need to find a way to pass the Epoch Manager address between those two jobs.

**Comment by neysofu** [comment]
I'll turn this into a PR draft to reflect the current state of things. It's quite close to done, but as you've seen there's still a few missing pieces.

More than an in-depth review of the manifest, I was hoping to collect some feedback on the idea of using `docker-compose`. We have a bit of a reproducibility problem in the block oracle, and a fully orchestrated solution like this one could imho really help us debug things.

**Comment by tilacog** [comment]
I like the idea of using docker-compose, it would help us achieve reproducibility.

**Comment by tilacog** [comment]
Another possible workaround is to make the Epoch Manager address deterministic.

We should be able to have that if hardhat inputs are always the same until the Epoch Manager gets deployed.

For this, we would probably need to start hardhat with `auto-mining` off to deploy the contracts. We can turn it on after that.

**Comment by neysofu** [comment]
I don't think we will need deterministic behavior. I'm thinking about spawnining a service that reuses the script logic to get the contract address and then passes it on to the `block-oracle` service via file/HTTP request.

**Comment by neysofu** [comment]
Some patterns are indeed a bit more complicated, but the number of examples on the web + containerization makes it really easy to experiment with solutions without breaking the whole thing.

**Comment by tilacog** [comment]
We could use a redis service to passe values around containers, but I think that going for a deterministic deployment (that would always produce the same address, as we already have for the owner private key) would be worth the shot.

**Comment by tilacog** [comment]
If we were to aim deterministic addresses, we could try:
- setting automine off in `hardhat.conig.ts`
- deploy the contracts in a deterministic order
- turn automine on using [this JRPC call](https://hardhat.org/hardhat-network/docs/explanation/mining-modes#using-rpc-methods).

**Comment by tilacog** [comment]
update:
I managed to get deterministic addresses :+1: 
All I did was set this config:
```
networks.hardhat.mining: {    
   auto: true,
   interval: 0
 }            
 ```

**Comment by neysofu** [comment]
Well, let's do it then! I thought it would be harder 😄

**Comment by neysofu** [comment]
Let me try that now.

**Comment by neysofu** [comment]
I can't fish the would-be-address out of the `docker-compose` logs, do you have it already by any chance?

**Comment by tilacog** [comment]
Just a recap and some corrections to what I said earlier:

- `mining.auto` is for automatically mining a new block whenever hardhat receives a transaction. With this turned on, we get one block for each txn.

- `mining.interval` is how often hardhat will mine a block, even it there are no transactions in the mempool. We want this turned off while we deploy the contracts, and then we must turn it back on with a JRPC call.


We could tweak the duration of each epoch by changing [this config value](https://github.com/graphprotocol/contracts/blob/358a8ec17d0f79e63cd9eed3fc6539f703c0ce8c/config/graph.localhost.yml#L49) in the contracts repo.

**Comment by tilacog** [comment]
epoch manager: `0xC89Ce4735882C9F0f0FE26686c53074E09B0D550`
data edge: `0xe78a0f7e598cc8b0bb87894b0f60dd2a88d6a8ab`

**Comment by neysofu** [comment]
So, basically must use those value in the `config.dev.toml` and then spawn a short-lived service that does a JRPC call to turn auto-mining back on? Is that it?

**Comment by tilacog** [comment]
Yes, we still need to send an HTTP request to turn hardhat back on.
We could also do this by code, using a hardhat script, but I think an HTTP request seems easier.

oh, and those addresses were a result of deploying the (eventful) DataEdge before the rest of the contracts

**Comment by neysofu** [comment]
Ready for (hopefully) final review.

**Pull request merged**
